[tool.poetry]
name = "openai-models-ja"
version = "0.1.0"
description = ""
authors = ["Goto Hayato <gh640@hey.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
